// Dogfoods `npm pack --dry-run` against the real repo: package.json's `files` array
// states packaging INTENT, but npm additionally auto-includes a small fixed set
// (package.json, README.md, LICENSE, the `main` entry) and otherwise honors `files`
// literally — a file everyone assumes ships (because the repo generates it, because
// it "obviously" should) can still be silently absent from the real tarball. Static
// assertions against package.json#files would only re-check the config's own stated
// intent, not what a consumer actually receives — this test runs the real packaging
// command instead (closes issue #134: CHANGELOG.md wasn't shipped in the npm tarball).

import { execFileSync } from 'node:child_process'
import * as path from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = path.resolve(import.meta.dirname, '..')

interface NpmPackEntry {
  readonly path: string
}
interface NpmPackResult {
  readonly files: readonly NpmPackEntry[]
}

const packedFiles = (): string[] => {
  const stdout = execFileSync('npm', ['pack', '--dry-run', '--json', '--ignore-scripts'], {
    cwd: repoRoot,
    encoding: 'utf8',
  })
  // The "prepare" lifecycle script (lefthook install) writes its own line to stdout
  // ahead of npm's JSON, even with --ignore-scripts on this npm version — npm's JSON
  // itself always starts with a lone "[" on its own line, so slice from there.
  const jsonStart = stdout.indexOf('\n[')
  const [result] = JSON.parse(jsonStart === -1 ? stdout : stdout.slice(jsonStart + 1)) as NpmPackResult[]
  return (result?.files ?? []).map((f) => f.path)
}

describe('the real npm tarball (not just package.json#files) contains what consumers need', () => {
  it('includes CHANGELOG.md, generated by changesets on every release', () => {
    expect(packedFiles()).toContain('CHANGELOG.md')
  })
})
